steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/pure-talent-453414-u7/my-repo/myimage', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/pure-talent-453414-u7/my-repo/myimage' ]

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'flask-app', '--image', 'us-central1-docker.pkg.dev/pure-talent-453414-u7/my-repo/myimage', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated' ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
